user: gsv
group: gsv

# where to store downloaded software distributions
distribution_dir: /stuff/software

java_deployment_root: /usr/lib/jvm

# where vms are stored or will be stored
virtualbox_vms_dir: /stuff/vm

# parent of the snapshots dir should exists
backup_snapshots_dir: /backup/snapshots/dev2
